# Generated by Django 2.2.7 on 2019-11-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_rating_array'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='work_place',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
