# Generated by Django 2.2.7 on 2019-11-16 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191116_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unver', to=settings.AUTH_USER_MODEL),
        ),
    ]
