# Generated by Django 2.2.7 on 2019-11-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='spec',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
